# Build configuration
[build]
  # Directory containing your build output (main directory in this case)
  publish = "."

  # Directory containing your Netlify Functions
  functions = "netlify/functions"

# Functions directory
[functions]
  directory = "netlify/functions"

# Redirect rules
[[redirects]]
  # Redirect all API calls to Netlify Functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables
[context.production.environment]
  ENGAGEBAY_API_KEY = "oivjchbsg4i5qb8hjoslnslaar"  # Replace with your actual EngageBay API key

# Headers to improve security
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
